# https://github.com/localstack/localstack/blob/master/docker-compose.yml
version: "3.8"

services:
  localstack:
    # v0.12.16
    image: localstack/localstack@sha256:22e869ce3ef9782ea05fd0cc1ea47ed713a205c5e8a9f7d319afcd9bbadedae0
    # network_mode: bridge
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "4566:4566"
      - "4571:4571"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  shell:
    build:
      context: .
      args: 
        - AWS_CLI_VER=2.2.31
        - TERRAFORM_VER=1.0.5
    depends_on: 
      - localstack
    hostname: docker-challenges
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=mock_access_key
      - AWS_SECRET_ACCESS_KEY=mock_secret_key
    volumes: 
      - ${PWD}/challenges:/challenges
