# https://github.com/localstack/localstack/blob/master/docker-compose.yml
version: "3.8"

services:
  localstack:
    # v0.12.16
    image: localstack/localstack@sha256:22e869ce3ef9782ea05fd0cc1ea47ed713a205c5e8a9f7d319afcd9bbadedae0
    # network_mode: bridge
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "4566:4566"
      - "4571:4571"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  shell:
    build: .
    entrypoint: bash
    depends_on: 
      - localstack
